[keyboard]
name = "lunakbd"
product_name = "lunakbd"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "gbpagano"
# chip = "nrf52840"
board = "nice!nano_v2"

[layout]
rows = 5
cols = 12
layers = 6
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5)        (0,11) (0,10) (0,9) (0,8) (0,7) (0,6)
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5)        (1,11) (1,10) (1,9) (1,8) (1,7) (1,6)
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5)        (2,11) (2,10) (2,9) (2,8) (2,7) (2,6)
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5)        (3,11) (3,10) (3,9) (3,8) (3,7) (3,6)
               (4,0) (4,1) (4,2) (4,3)  (4,11) (4,10) (4,9) (4,8)
"""

[ble]
enabled = true

[behavior.morse]
enable_flow_tap = false
hold_on_other_press = true
hold_timeout = "200ms"
gap_timeout = "200ms"

[storage]
enabled = true
clear_storage = false

[split]
connection = "ble"

[split.central]
rows = 0
cols = 0
row_offset = 0
col_offset = 0
[split.central.matrix]
matrix_type = "normal"
row_pins = []
col_pins = []

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 0
[split.peripheral.matrix]
matrix_type = "normal"
col_pins = ["P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
row_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04"]
[[split.peripheral.input_device.encoder]]
pin_a = "P0_31"
pin_b = "P0_29"
phase = "resolution"
resolution = 4
internal_pullup = true

[[split.peripheral]]
rows = 5
cols = 6
row_offset = 0
col_offset = 6
[split.peripheral.matrix]
matrix_type = "normal"
col_pins = ["P0_02", "P1_15", "P1_13", "P1_11", "P0_10", "P0_09"]
row_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04"]
[[split.peripheral.input_device.encoder]]
pin_a = "P0_29"
pin_b = "P0_31"
phase = "resolution"
resolution = 4
internal_pullup = true
